name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      
      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py

          echo "## Scores" > report.md
          cat scores.txt >> report.md
          
          echo "## Scores vizualization" > report.md
          cml-publish scores.png --md >> report.md
          cml-send-comment report.md

